#!/usr/bin/env python3
"""Regenerate INDEX.md from the entries tree.

    python tools/build_index.py

INDEX.md is generated. Do not edit it by hand; edit the entries instead.
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install -r tools/requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
ENTRIES = ROOT / "entries"
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)

REGION_NAMES = {
    "1": "Region 1 - Property-Level",
    "2": "Region 2 - Investment-Level",
    "3": "Region 3 - Partnership-Level",
}

BADGE = {
    "stub": "stub",
    "draft": "draft",
    "reviewed": "reviewed",
    "ratified": "**ratified**",
}


def sort_key(entry_id: str) -> tuple[int, ...]:
    return tuple(int(p) for p in entry_id.split("."))


def main() -> int:
    sections: dict[str, list[dict]] = defaultdict(list)
    section_titles: dict[str, str] = {}

    for path in ENTRIES.rglob("*.md"):
        if path.name in ("TEMPLATE.md", "SECTION.md"):
            continue
        match = FRONTMATTER_RE.match(path.read_text(encoding="utf-8"))
        if not match:
            continue
        meta = yaml.safe_load(match.group(1)) or {}
        section = str(meta.get("section", ""))
        sections[section].append(
            {
                "id": str(meta.get("id", "")),
                "name": meta.get("name", ""),
                "status": str(meta.get("status", "")),
                "path": path.relative_to(ROOT).as_posix(),
            }
        )

    for folder in ENTRIES.rglob("SECTION.md"):
        first = folder.read_text(encoding="utf-8").splitlines()[0]
        m = re.match(r"^#\s+([\d.]+)\s+(.*)$", first)
        if m:
            section_titles[m.group(1)] = m.group(2)

    total = sum(len(v) for v in sections.values())
    counts: dict[str, int] = defaultdict(int)
    for items in sections.values():
        for item in items:
            counts[item["status"]] += 1

    lines = [
        "# Index",
        "",
        "Generated by `tools/build_index.py`. Do not edit by hand.",
        "",
        f"{total} entries: "
        + ", ".join(
            f"{counts[s]} {s}" for s in ("stub", "draft", "reviewed", "ratified") if counts[s]
        )
        + ".",
        "",
    ]

    current_region = None
    for section in sorted(sections, key=lambda s: tuple(int(p) for p in s.split("."))):
        region = section.split(".")[0]
        if region != current_region:
            current_region = region
            lines += [f"## {REGION_NAMES.get(region, region)}", ""]

        title = section_titles.get(section, "")
        lines += [f"### {section} {title}".rstrip(), ""]
        lines += ["| ID | Line item | Status |", "|---|---|---|"]
        for item in sorted(sections[section], key=lambda e: sort_key(e["id"])):
            badge = BADGE.get(item["status"], item["status"])
            lines.append(f"| {item['id']} | [{item['name']}]({item['path']}) | {badge} |")
        lines.append("")

    (ROOT / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"INDEX.md written: {total} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
